language: ruby
rvm:
  - 2.2.5
  - 2.3.1
script: 
  - "rake lint"
  - "rake spec"
  - "rake validate"
branches:
  only:
    - master
env:
  - PUPPET_GEM_VERSION="~> 4.6.1"
  - PUPPET_GEM_VERSION="~> 4.8"
  - PUPPET_GEM_VERSION="~> 4.10"
notifications:
  email: false
gemfile: .gemfile
